title:               João Pedro Peters Barbosa
url:                 https://joaoppeters.github.io
baseurl:             ""
google_analytics:    G-27XVDEWHP0

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              João Pedro Peters Barbosa
  url:               joaoppeters.github.io
  email:             joao.peters@ieee.org

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist